# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4d08679929ad853d274db3eee24057b9"
name = "my-test-app"
application_url = "https://dimensional-assuming-plots-newly.trycloudflare.com"
embedded = true
handle = "my-test-app-1350"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dimensional-assuming-plots-newly.trycloudflare.com/auth/callback",
  "https://dimensional-assuming-plots-newly.trycloudflare.com/auth/shopify/callback",
  "https://dimensional-assuming-plots-newly.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
